name: Tests (Bun)

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - '**'
    tags:
      - '!**'

jobs:
  test:
    runs-on: ubuntu-latest
    name: ubuntu-latest (Node v20)

    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
      - run: bun install
      # - run: bun run lint
      - run: bun run build
      - run: bun run knip
      # - run: bun run knip:production
      - run: bun run test
